import { EXERCISES } from '../workouts';

export const Exercises: EXERCISES[] = [
  {
    name: 'Deadlift',
  },
  {
    name: 'squat',
  },
  {
    name: 'benchpress',
  },
  {
    name: 'rows',
  },
  {
    name: 'pull up',
  },
  {
    name: 'lat pull down',
  },
  {
    name: 'bicep curl',
  },
  {
    name: 'tricep extension',
  },
  {
    name: 'military press',
  },
  {
    name: 'leg press',
  },
  {
    name: 'leg curl',
  },
  {
    name: 'leg extension',
  },
  {
    name: 'abs',
  }
];
export const exerciseArray : string[] = [
  "Deadlift",
  "Squat",
  "bench press",
  "Leg Curl",
  "Lying Leg Curl",
  "Seated Leg Curl",
  "Hack Squat",
  "Barbell Squat  ",
  "Dumbbell Lunge  ",
  "Dumbbell Step-Up  ",
  "Leg Press  ",
  "Lunge  ",
  "Single-Leg Box Squat  ",
  "Walking Lunge  ",
  "Alternating Leg Extension  ",
  "Leg Extension  ",
  "Calf Raise - Seated  ",
  "Calf Raise - Standing  ",
  "Assisted Pull-Up  ",
  "Close-Grip Lat Pulldown  ",
  "Lat Pulldown  ",
  "Wide-Grip Lat Pulldown  ",
  "Pull-Up  ",
  "Bent-Over Alternating Dumbbell Row  ",
  "Bent-Over Barbell Row  ",
  "Bent-Over Dumbbell Row  ",
  "One Arm Dumbbell Row  ",
  "Seated Cable Row  ",
  "Seated Row  ",
  "face pulls",
  "back extension",
  "Dumbbell Bench Press  ",
  "Barbell Bench Press  ",
  "Incline Dumbbell Bench Press  ",
  "Push-Up  ",
  "Cable Crossover  ",
  "Cable Fly  ",
  "Decline Dumbbell Fly  ",
  "High Cable Crossover  ",
  "Incline Cable Fly  ",
  "Pec Deck  ",
  "Barbell Shoulder Press",
  "Dumbbell Shoulder Press  ",
  "Cable Front Raise  ",
  "Dumbbell Lateral Raise  ",
  "Single-Arm Cable Lateral Raise  ",
  "Barbell Curl",
  "Dumbbell Curl",
  "Cable Curl",
  "EZ-Bar Curl  ",
  "Hammer Curl  ",
  "Preacher Dumbbell Curl  ",
  "Reverse Curl  ",
  "Bench Dips  ",
  "Dumbbell Kickback  ",
  "Overhead Dumbbell Triceps Extension  ",
  "Rope Triceps Pushdown  ",
  "skull crusher",
  "Alternating Heel Touch  ",
  "Cable Chop",
  "Ab wheel",
  "V-Up",
  "Crunch",
  "Sit-Up",
];

export const legs : string[] = [
  "Leg Curl",
  "Lying Leg Curl",
  "Seated Leg Curl",
  "Hack Squat",
  "Barbell Squat  ",
  "Dumbbell Lunge  ",
  "Dumbbell Step-Up  ",
  "Leg Press  ",
  "Lunge  ",
  "Single-Leg Box Squat  ",
  "Walking Lunge  ",
  "Alternating Leg Extension  ",
  "Leg Extension  ",
  "Calf Raise - Seated  ",
  "Calf Raise - Standing  ",
]
export const back : string[] = [
  "Assisted Pull-Up",
  "Close-Grip Lat Pulldown",
  "Lat Pulldown ",
  "Wide-Grip Lat Pulldown",
  "Pull-Up ",
  "Bent-Over Alternating Dumbbell Row",
  "Bent-Over Barbell Row",
  "Bent-Over Dumbbell Row",
  "One Arm Dumbbell Row",
  "Seated Cable Row",
  "Seated Row",
  "face pulls",
  "Deadlift",
  "back extension",
];
export const chestShoulder : string[] = [
  "Dumbbell Bench Press",
  "Barbell Bench Press",
  "Incline Dumbbell Bench Press",
  "Push-Up",
  "Cable Crossover",
  "Cable Fly",
  "Decline Dumbbell Fly",
  "High Cable Crossover",
  "Incline Cable Fly",
  "Pec Deck",
  "Barbell Shoulder Press",
  "Dumbbell Shoulder Press  ",
  "Cable Front Raise",
  "Dumbbell Lateral Raise",
  "Single-Arm Cable Lateral Raise",
];
export const arms : string[] = [
  "Barbell Curl",
  "Dumbbell Curl",
  "Cable Curl",
  "EZ-Bar Curl",
  "Hammer Curl",
  "Preacher Dumbbell Curl",
  "Reverse Curl",
  "Bench Dips",
  "Dumbbell Kickback",
  "Overhead Dumbbell Triceps Extension  ",
  "Rope Triceps Pushdown",
  "skull crusher",
]
export const abs : string[] = [
  "Alternating Heel Touch",
  "Cable Chop",
  "Ab wheel",
  "V-Up",
  "Crunch",
  "Sit-Up",
]
