import { cooking } from "./interfaces"
export const meals : cooking[] = [
    {id:1,rating:3,time:"10min",name:"DOUBLE CHOCOLATE OVERNIGHT OATS",img:"https://www.budgetbytes.com/wp-content/uploads/2022/03/Double-Chocolate-Overnight-Oats-V2-768x1024.jpg",
    ingredients:["1 1/3 cup rolled oats","2 Tbsp unsweetened cocoa powder","2 Tbsp brown sugar","1/4 cup mini chocolate chips","1/4 tsp salt","1 1/3 cup milk","1/2 tsp vanilla extract"],
    howTo:["Combine the oats, chia seeds, cocoa powder, brown sugar, chocolate chips, and salt in a bowl.","Add the milk and vanilla extract, then stir to combine. Allow the mixture to sit for about five minutes.","Divide the oat mixture between four resealable containers. Close the containers and refrigerate overnight or up to five days.","Stir the oats just before enjoying. Eat cold or warm it up in the microwave."],tags:["breakfast","easy","mealprep","healthy"]},
    {id:2,rating:3.5,time:"1h",name:"SMOKY CHICKEN AND CINNAMON ROASTED SWEET POTATO MEAL PREP",img:"https://www.budgetbytes.com/wp-content/uploads/2018/05/Smoky-Chicken-and-Cinnamon-Roasted-Sweet-Potato-meal-prep-single-500x500.jpg",ingredients:["2 sweet potatoes","1 Tbsp cooking oil","1/2 tsp cinnamon","pinch cayenne pepper","pinch salt","1 tsp smoked paprika","1 tsp brown sugar","1/4 tsp garlic powder","2 boneless, skinless chicken breasts","1 lb. green beans","1 Tbsp butter "],
    howTo:["Preheat the oven to 400ºF. Wash the sweet potatoes, pat them dry, and prick their skins a few times with a fork. Slice the sweet potatoes in half lengthwise, then place them on a baking sheet. Drizzle the cooking oil over the potatoes, then use your hands to smear the oil over their entire surface (skin and cut sides), leaving a liberal amount of oil on the baking sheet under the potatoes to keep them from sticking.","Place the sweet potatoes with the cut side up, then sprinkle with cinnamon, a pinch of cayenne pepper, and a pinch of salt. Flip the sweet potatoes over so they are cut side down, then roast for 45-50 minutes, or until they are soft all the way through and the juices are caramelized and bubbling out of the holes in the skin.","While the sweet potatoes are roasting, prepare the chicken and green beans. Combine the spices for the chicken in a small bowl (smoked paprika, brown sugar, garlic powder, cayenne, salt, and freshly ground pepper-about 20 cranks of a pepper mill).","Pat the chicken dry, then sprinkle the spice rub over both sides. Heat a large skillet over medium, then add the cooking oil and swirl to coat the surface. Add the chicken and cook until they are deeply browned on each side and the internal temp has reached 165ºF. Remove the chicken to a cutting board and let it rest.","While the chicken is cooking, prepare the green beans. Add about one inch water to a sauce pot and place a steaming basket in the pot. Add the green beans to the basket, place a lid on top, and place them over medium-high heat. Allow the water to come up to a boil and steam the green beans for 7-10 minutes, or until they are bright green and only slightly softened.","Remove the green beans from the pot, pour out the water, and place the beans back in the pot without the steaming basket. Add 1 Tbsp butter and allow the residual heat from the beans to melt the butter. Stir to coat, then season with a pinch of salt and pepper.","Slice the chicken breasts into strips. Divide the sweet potato halves, green beans, and chicken between four containers or plates. Serve immediately or refrigerate and reheat later."],tags:["mealprep","healthy","lunch","chicken"]},
    {id:3,rating:4.5,time:"30min",name:"Sweet and Sour Chicken",img:"https://www.tasteandtellblog.com/wp-content/uploads/2015/06/Sweet-and-Sour-Chicken-Recipe-tasteandtellblog.com-1-new.jpg",
    ingredients:["1/2 Cup (125ml) - Light Soy Sauce ","1/3 Cup (80ml) - Pineapple Juice","4 Tbsp (80g) - Honey","2 Tbsp (40ml) - Worcestershire Sauce","2 Tbsp (40ml) - Apple Cider Vinegar","2 Tbsp (40g) - Tomato Ketchup","2 Tbsp (12g) - Corn Flour or Corn Starch","2 1/2 Tbsp (50ml) - Grapeseed Oil, Divided","1.4kg (3.09lbs) - Chicken Breast or Thigh, Diced","3 - Bell Peppers","1 - Brown (Yellow) Onion","4 - Garlic Cloves, Minced","15g (0.53oz) - Ginger, Peeled & Minced","300g rice"],
    howTo:["boil rice","Sweet & Sour Sauce. throw all sauce ingredients together:Light Soy Sauce, Pineapple Juice, Honey, Worcestershire Sauce, Apple Cider Vinegar, Tomato Ketchup, Corn Flour or Corn Starch","heat bell peppers and onion on skillet. take out and start cooking chicken","when chicken is cooked throw in bell peppers, onion, garlic, ginger and lastly sauce.","heat for few minutes. optional add sesame seeds" ],tags:["chicken","mealprep","lunch","healthy"]},
    {id:4,rating:4.5,time:"15min",name:"Beef Stir Fry Recipe",img:"https://www.wellplated.com/wp-content/uploads/2020/05/Beef-Stir-Fry.jpg",ingredients:["1kg (2.2lbs) - Beef Mince","1 - Brown (Yellow) Onion","1 - Red Bell Pepper","1 - Carrot","1 - Bunch Broccolini, Chopped (300g)","100ml (100g) - Low Sodium Soy Sauce ","2 Tbsp (40ml) - Rice Vinegar","70g (2.4oz) - Brown Sugar","5 - Cloves Garlic, Minced","15g (0.5oz) - Ginger, Minced","rice"],
    howTo:["make sauce by mixing all incredients:  Soy Sauce, Rice Vinegar, Brown Sugar, garlic minced, ginger minced","boil rice","start cooking minced meat after its brown add in onion slices, grated carrot , Bell pepper cut","heat few minutes and add sauce. optional add sesame seeds"],tags:["mealprep","lunch","healthy","beef"]},
    {id:5,rating:2,time:"5min",name:"4-Ingredient Quick Nutella Mug Cake",img:"https://www.thecomfortofcooking.com/wp-content/uploads/2014/08/1MinuteNutellaMugCake-600x854.jpg",ingredients:["1/4 cup all-purpose flour","1/4 cup Nutella","3 Tablespoons milk","1/4 teaspoon baking powder"],howTo:["Combine all ingredients in an oversized mug or heatproof bowl. Whisk with a fork until smooth (batter will be thick). Microwave on high for 1 to 1-1/2 minutes (Start with 1 minute, then check for doneness and cook for more time, if necessary). A toothpick inserted into cake center should come out clean. Let cool slightly before eating.","enjoy"],tags:["easy","dessert"]},
    {id:6,rating:4,time:"20min",name:"Chicken curry",img:"https://www.chelseasmessyapron.com/wp-content/uploads/2015/02/Chicken-Curry-3.jpg",ingredients:["800g chicken cut","250g green beans","3 spoons currypaste","400ml coconut milk","rice"],howTo:["Cut up the chicken fillets and remove the hard end pieces from the beans.","Heat the oil in a saucepan. Add 3 tablespoons of curry paste and heat. Add the chicken, stir and fry for a couple of minutes.","Add the coconut milk, 1dl water and . Bring to the boil and cook for 5 minutes. Add the beans and cook for another 5 minutes. Season with fish sauce.","Sprinkle with fresh basil and serve with basmati rice."],tags:["chicken","easy","lunch"]},
    {id:7,rating:4,time:"30 - 60 min",name:"Berry pie",ingredients:["100g cooking margarine","4dl wheat flour","2 1/2dl sugar","1tl baking powder","1tl soda","1tl vanillin sugar","1 1/2dl flavourless yogurt","2 eggs","250g quark/maitorahkaa","400g berries"],
    howTo:["Melt the cooking margarine in the microwave in a baking dish and allow to cool. Mix the dry ingredients together and add to the cooking margarine. Take about 1/3 of the crumb mixture separately. Mix the yoghurt and egg into the crumble mixture.","Spread the yoghurt dough in a pie dish (diameter 30 cm).","Mix together the curd, sugar, egg and vanilla sugar. Spread the curd mixture over the base. Sprinkle the iced or souffled berries (chopped strawberries) and crumbled toast over the top. Bake at 175°C on the lowest setting of the oven for about 45 minutes. Serve with custard or ice cream if you like."],tags:["dessert"],img:"https://public.keskofiles.com/f/recipe/PI4_marjapiiras?w=1440&fit=crop&q=60&auto=format&fm=jpg&ar=16%3A7"}, 



]

/* {id:1,rating:5,time:"",name:"",ingredients:["",""],howTo:["",""],tags:["",""],img:""}, */