import { rlyDunno } from "../workouts";

export const gymWorkout : rlyDunno[] = [
    {id:1,workout:[{sets:5,reps:"5",setsDone:0,done:false,exercise:"Squat"},{sets:5,reps:"5",setsDone:0,done:false,exercise:"Bench press"},{sets:5,reps:"5",setsDone:0,done:false,exercise:"Barbell row"}]},
    {id:2,workout:[{sets:5,reps:"5",setsDone:0,done:false,exercise:"Squat"},{sets:5,reps:"5",setsDone:0,done:false,exercise:"overhead press"},{sets:5,reps:"1",setsDone:0,done:false,exercise:"Deadlift"}]},
    {id:3,workout:[{sets:5,reps:"5",setsDone:0,done:false,exercise:"Squat"},{sets:5,reps:"5",setsDone:0,done:false,exercise:"Bench press"},{sets:5,reps:"5",setsDone:0,done:false,exercise:"barbell row"}]},
    {id:4,workout:[{sets:5,reps:"5",setsDone:0,done:false,exercise:"Squat"},{sets:5,reps:"5",setsDone:0,done:false,exercise:"overhead press"},{sets:5,reps:"1",setsDone:0,done:false,exercise:"Deadlift"}]},
    {id:5,workout:[{sets:5,reps:"5",setsDone:0,done:false,exercise:"Squat"},{sets:5,reps:"5",setsDone:0,done:false,exercise:"bench press"},{sets:5,reps:"5",setsDone:0,done:false,exercise:"barbell row"}]},
    {id:6,workout:[{sets:5,reps:"5",setsDone:0,done:false,exercise:"Squat"},{sets:5,reps:"5",setsDone:0,done:false,exercise:"overhead press"},{sets:5,reps:"1",setsDone:0,done:false,exercise:"Deadlift"}]},
    {id:7,workout:[{sets:4,reps:"8-10",setsDone:0,done:false,exercise:"Flat Barbell Bench Press"},{sets:3,reps:"12",setsDone:0,done:false,exercise:"Incline Bench Press"},{sets:3,reps:"12",setsDone:0,done:false,exercise:"Seated Shoulder Press"}
    ,{sets:3,reps:"10-12",setsDone:0,done:false,exercise:"Flat Bench Dumbell Flyes"},{sets:3,reps:"10-12",setsDone:0,done:false,exercise:"Standing Dumbell Lateral Raises"},{sets:3,reps:"12-15",setsDone:0,done:false,exercise:"Tricep Rope Pushdown"},{sets:3,reps:"12",setsDone:0,done:false,exercise:"EZ Bar Skullcrusher"}]},
    {id:8,workout:[{sets:3,reps:"8",setsDone:0,done:false,exercise:"Barbell Row"},{sets:3,reps:"8",setsDone:0,done:false,exercise:"Neutral Lat Pulldown"},{sets:2,reps:"12-15",setsDone:0,done:false,exercise:"Dumbbell Shrug"},
{sets:2,reps:"12",setsDone:0,done:false,exercise:"Face Pull"},{sets:3,reps:"8-12",setsDone:0,done:false,exercise:"Barbell Curl"},{sets:3,reps:"12-15",setsDone:0,done:false,exercise:"Hammer Curl"},{sets:3,reps:"12-15",setsDone:0,done:false,exercise:"Leg Raises"}]},
    {id:9,workout:[{sets:3,reps:"8",setsDone:0,done:false,exercise:"Barbell Squat"},{sets:3,reps:"10-12",setsDone:0,done:false,exercise:"Romanian Deadlift"},{sets:3,reps:"8-10",setsDone:0,done:false,exercise:"Leg Press"}
    ,{sets:3,reps:"10-12",setsDone:0,done:false,exercise:"Barbell Lunges"},{sets:3,reps:"15-20",setsDone:0,done:false,exercise:"Leg Curl"},{sets:3,reps:"10-12",setsDone:0,done:false,exercise:"Calf press"}]},
    {id:10,workout:[{sets:4,reps:"6",setsDone:0,done:false,exercise:"Deadlift"},{sets:4,reps:"8-12",setsDone:0,done:false,exercise:"Lat Pull Down"},{sets:4,reps:"8-12",setsDone:0,done:false,exercise:"dumbbell Row"},{sets:4,reps:"10",setsDone:0,done:false,exercise:"machine row"},{sets:3,reps:"12",setsDone:0,done:false,exercise:"One Arm Cable Row"},{sets:2,reps:"15",setsDone:0,done:false,exercise:"Straight Arm Cable Pull Down"},]},
    {id:11,workout:[{sets:4,reps:"6",setsDone:0,done:false,exercise:"Incline Bench Press"},{sets:4,reps:"8-12",setsDone:0,done:false,exercise:"Decline Bench Press"},{sets:3,reps:"12",setsDone:0,done:false,exercise:"Bench Press"},{sets:3,reps:"12",setsDone:0,done:false,exercise:"chest fly"},{sets:3,reps:"failure",setsDone:0,done:false,exercise:"Push Ups"},{sets:3,reps:"12",setsDone:0,done:false,exercise:"hanging Leg Raise"},]},
    {id:12,workout:[{sets:5,reps:"6",setsDone:0,done:false,exercise:"Barbell Back Squat"},{sets:4,reps:"8-12",setsDone:0,done:false,exercise:"Romanian Deadlift"},{sets:3,reps:"10-15",setsDone:0,done:false,exercise:"Leg Press"},{sets:3,reps:"12-15",setsDone:0,done:false,exercise:"Leg Curl"},{sets:3,reps:"15",setsDone:0,done:false,exercise:"Walking Lunge"},{sets:4,reps:"20",setsDone:0,done:false,exercise:"calf raise"},]},
    {id:13,workout:[{sets:4,reps:"6",setsDone:0,done:false,exercise:"Military Press"},{sets:4,reps:"8-12",setsDone:0,done:false,exercise:"Lateral Raise"},{sets:4,reps:"4-12",setsDone:0,done:false,exercise:"Reverse Machine Fly"},{sets:4,reps:"12",setsDone:0,done:false,exercise:"Cable Front Raise"},{sets:4,reps:"15",setsDone:0,done:false,exercise:"Shrugs"},{sets:3,reps:"15",setsDone:0,done:false,exercise:"Decline Sit Up"},{sets:3,reps:"12",setsDone:0,done:false,exercise:"ab wheel"}]},
    {id:14,workout:[{sets:4,reps:"8-12",setsDone:0,done:false,exercise:"EZ Bar Curl"},{sets:4,reps:"8-12",setsDone:0,done:false,exercise:"EZ Bar Skullcrusher"},{sets:4,reps:"12",setsDone:0,done:false,exercise:"Hammer Curl"},{sets:4,reps:"12",setsDone:0,done:false,exercise:"Tricep Dip"},{sets:4,reps:"12",setsDone:0,done:false,exercise:"wrist Extension"},{sets:4,reps:"8-12",setsDone:0,done:false,exercise:"Cable Overhead Tricep Extension"},]},
    {id:15,workout:[{sets:3,reps:"10",setsDone:0,done:false,exercise:"Incline Barbell Bench Press"},{sets:3,reps:"12",setsDone:0,done:false,exercise:"Dumbbell Fly"},{sets:3,reps:"12",setsDone:0,done:false,exercise:"Weighted Dip"},{sets:3,reps:"12",setsDone:0,done:false,exercise:"Pec-Deck"},{sets:3,reps:"12",setsDone:0,done:false,exercise:"Cable Crossover"},{sets:3,reps:"12",setsDone:0,done:false,exercise:"Hanging Leg Raise"},{sets:3,reps:"15",setsDone:0,done:false,exercise:"Side Bends"},{sets:3,reps:"failure",setsDone:0,done:false,exercise:"Plank"},{sets:3,reps:"15",setsDone:0,done:false,exercise:"Rope Crunch"},]},
    {id:16,workout:[{sets:3,reps:"failure",setsDone:0,done:false,exercise:"Neutral Grip Pullups"},{sets:3,reps:"12",setsDone:0,done:false,exercise:"Bent Over Barbell Row"},{sets:3,reps:"12",setsDone:0,done:false,exercise:"Straight Arm Pulldown"},{sets:3,reps:"12",setsDone:0,done:false,exercise:"Wide Grip Seated Row"},{sets:3,reps:"15",setsDone:0,done:false,exercise:"Deadlift"}]},
    {id:17,workout:[{sets:3,reps:"10",setsDone:0,done:false,exercise:"Lateral Raise 3x10"},{sets:3,reps:"12",setsDone:0,done:false,exercise:"Shoulder Press"},{sets:3,reps:"12",setsDone:0,done:false,exercise:"Front Plate Raise"},{sets:3,reps:"12",setsDone:0,done:false,exercise:"High Rope Face Pull"}]},
    {id:18,workout:[{sets:3,reps:"12",setsDone:0,done:false,exercise:"EZ Bar Preacher Curl"},{sets:3,reps:"12",setsDone:0,done:false,exercise:"Close Grip Bench Press"},{sets:3,reps:"12",setsDone:0,done:false,exercise:"Hammer Curl"},{sets:3,reps:"12",setsDone:0,done:false,exercise:"Overhead Rope Extension"},{sets:3,reps:"15",setsDone:0,done:false,exercise:"Reverse Grip Pushdown"}]},
    {id:19,workout:[{sets:3,reps:"8",setsDone:0,done:false,exercise:"Squat"},{sets:3,reps:"15",setsDone:0,done:false,exercise:"Leg Press"},{sets:3,reps:"15",setsDone:0,done:false,exercise:"Single Leg Extension"},{sets:3,reps:"15",setsDone:0,done:false,exercise:"Seated Leg Curl"},{sets:3,reps:"15",setsDone:0,done:false,exercise:"Lying Leg Curl"},{sets:3,reps:"20",setsDone:0,done:false,exercise:"Calf raise"}]}








]

/* {sets:3,setsDone:0,done:false,exercise:""}, */