import { guide } from "../workouts"
export const info : guide[] = [
    {name:"Deadlift",description:"weight training exercise in which a loaded barbell or bar is lifted off the ground to the level of the hips, torso perpendicular to the floor, before being placed back on the ground.",link:"https://www.youtube.com/embed/vRKDvt695pg"},
    {name:"Squat",description:"squat is a strength exercise in which the trainee lowers their hips from a standing position and then stands back up. During the descent, the hip and knee joints flex while the ankle joint dorsiflexes; conversely the hip and knee joints extend and the ankle joint plantarflexes when standing up. Squats also help your hip muscles",link:"https://www.youtube.com/embed/gsNoPYwWXeM"},
    {name:"Bench press",description:"The bench press, or chest press, is a weight training exercise where the trainee presses a weight upwards while lying on a weight training bench. Although the bench press is a full-body exercise, the muscles primarily used are the pectoralis major, the anterior deltoids, and the triceps, among other stabilizing muscles. A barbell is generally used to hold the weight, but a pair of dumbbells can also be used.",link:"https://www.youtube.com/embed/gRVjAtPip0Y"},
    {name:"barbell row",description:"Barbell Rows are a full body, compound exercise. They work your upper-back, lower back, hips and arms. They build a stronger, muscular back and bigger biceps. Barbell Rows are one of the most effective assistance exercises you can do to increase your Squat, Bench Press and Deadlift.",link:"https://www.youtube.com/embed/FWJR5Ve8bnQ"},
    {name:"overhead press",description:"The Overhead Press is a full body, compound exercise. Your shoulders and arms press the weight over your head while your legs, lower back and abs balance you. The Overhead Press is one of the best exercises to build strong, muscular and healthy shoulders with bigger arms.To avoid shoulder pain, Overhead Press with a narrow grip so you don't flare your elbows. Then shrug your shoulders at the top. Press the bar over your head, lock your elbows and shrug your shoulders towards the ceiling. This engages your traps and prevents shoulder impingement.",link:"https://www.youtube.com/embed/F3QY5vMz_6I"},
    {name:"neutral lat pulldown",description:"Our lats won't be able to engage if our torso is upright and our arms are pointing directly up. Like with pull-ups, we need to lean back slightly so that our shoulder socket is pointing a little upwards, allowing us to better engage the lats.When completing a rep, your main focus should be on pulling your elbows down to your sides. This cue will help you to activate your lats more, rather than recruiting other muscles like the biceps to help more than they should",link:"https://www.youtube.com/embed/kVB6SlEyjQM"},
    {name:"Face Pull",description:"Face pulls target the posterior deltoids of the shoulder, which are often neglected by other shoulder exercises. You use a cable pulley machine to pull the weight straight toward your forehead. Exercising the rear delts will prevent muscular imbalance and build overall shoulder strength. This exercise isn't hard to do as long as you pay attention to your form. You can use face pulls as part of an upper body strength training regimen.",link:"https://www.youtube.com/embed/rep-qVOkqgk"},
    {name:"lat pull down",description:"Our lats won't be able to engage if our torso is upright and our arms are pointing directly up. Like with pull-ups, we need to lean back slightly so that our shoulder socket is pointing a little upwards, allowing us to better engage the lats.When completing a rep, your main focus should be on pulling your elbows down to your sides. This cue will help you to activate your lats more, rather than recruiting other muscles like the biceps to help more than they should",link:"https://www.youtube.com/embed/kVB6SlEyjQM"},
    {name:"Romanian Deadlift",description:"Everyone should deadlift - yeah, we said it - but not everyone is ready to deadlift right away. “The Romanian deadlift, in my opinion, is easier to execute correctly than the conventional deadlift,” says Hoobler. “If someone was learning to deadlift, I would start them with this move, with the bar beginning on a rack. This way, they can eccentrically load first, where they're stronger and have more control.” The eccentric phase of the Romanian deadlift is the portion of the lift where the bar is being lowered to the floor. People are usually stronger in the portion of a lift.",link:"https://www.youtube.com/embed/2SHsk9AzdjA"},
    {name:"dumbbell row",description:"The dumbbell row, also known as the single-arm dumbbell row, is one of those exercises that will stay in style. It's simple as heck to do — you kneel on a bench and row your arm to your side — and it requires just a dumbbell to load the movement. It's also a unilateral exercise, which trains one side of your body simultaneously. Single-arm moves help to even out muscular imbalances and burn more calories over time since you're doubling your workload.",link:"https://www.youtube.com/embed/-koP10y1qZI"},
    {name:"machine row",description:"Machine row is a stable exercise for your pulling muscles, which means that you don't have to think about balance or trajectory, but can focus on getting contact with the right muscles.",link:"https://www.youtube.com/embed/A3M3sdXTT9Y"},
    {name:"one arm cable row",description:"one-arm cable row is a exercise machine exercise that primarily targets the middle back and to a lesser degree also targets the shoulders and triceps. The only one-arm cable row equipment that you really need is the following: cable machine. There are however many different one-arm cable row variations that you can try out that may require different types of one-arm cable row equipment or may even require no equipment at all.",link:"https://www.youtube.com/embed/CrylzZHfO1c"},
    {name:"Straight Arm Cable Pull Down",description:"The straight arm lat pull down is a variation of the lat pull down and an exercise used to build the muscles of the back. While the exercise will primarily target the lats, you will also notice a fair amount of bicep and middle back activation. The back is a muscle group that requires a fair amount of variation. So, experiment with several different angles and hand positions to maximize your back muscle growth.",link:"https://www.youtube.com/embed/r34PR1mxzmU"},



]
/* {name:"",description:"",link:""}, */